// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk-GeDEgQgDSsKO5HrW_DsR1z33rCWQh8',
    appId: '1:576819138333:web:1bda97a6d9a9ee081d5bf4',
    messagingSenderId: '576819138333',
    projectId: 'fixit-b4060',
    authDomain: 'fixit-b4060.firebaseapp.com',
    storageBucket: 'fixit-b4060.appspot.com',
    measurementId: 'G-4DV6ZRJBN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ_YcUu9AEHEWOda0oVlroDo1lvIZXmBA',
    appId: '1:576819138333:android:a17e67a1ad04ba661d5bf4',
    messagingSenderId: '576819138333',
    projectId: 'fixit-b4060',
    storageBucket: 'fixit-b4060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_tPY-MUOBc6gkF-b-DWfdr3xrqHTHUHc',
    appId: '1:576819138333:ios:ae84de0a96cb158e1d5bf4',
    messagingSenderId: '576819138333',
    projectId: 'fixit-b4060',
    storageBucket: 'fixit-b4060.appspot.com',
    androidClientId: '576819138333-4o0criciqcljleij4jb2hhd3jofba8j8.apps.googleusercontent.com',
    iosClientId: '576819138333-29hi45ifcg6f9cjundoi9q11t5ume9tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_tPY-MUOBc6gkF-b-DWfdr3xrqHTHUHc',
    appId: '1:576819138333:ios:ae84de0a96cb158e1d5bf4',
    messagingSenderId: '576819138333',
    projectId: 'fixit-b4060',
    storageBucket: 'fixit-b4060.appspot.com',
    androidClientId: '576819138333-4o0criciqcljleij4jb2hhd3jofba8j8.apps.googleusercontent.com',
    iosClientId: '576819138333-29hi45ifcg6f9cjundoi9q11t5ume9tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk-GeDEgQgDSsKO5HrW_DsR1z33rCWQh8',
    appId: '1:576819138333:web:4fcb7a7171fd0e341d5bf4',
    messagingSenderId: '576819138333',
    projectId: 'fixit-b4060',
    authDomain: 'fixit-b4060.firebaseapp.com',
    storageBucket: 'fixit-b4060.appspot.com',
    measurementId: 'G-LMF0DG3P7C',
  );

}